# Generated by Django 4.1.7 on 2023-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro_text',
            field=models.TextField(blank=True),
        ),
    ]
